### ISSUE TITLE
macos-alias@0.2.6 fails to compile on ubuntu 14.02

### ISSUE THREAD

**Issue by comamitc** [oakmac/cuttle#99]
```
> macos-alias@0.2.6 install /home/comamitc/dev/cuttle/node_modules/grunt-appdmg/node_modules/appdmg/node_modules/ds-store/node_modules/macos-alias
> node-gyp rebuild

make: Entering directory `/home/comamitc/dev/cuttle/node_modules/grunt-appdmg/node_modules/appdmg/node_modules/ds-store/node_modules/macos-alias/build'
  CXX(target) Release/obj.target/volume/src/volume.o
../src/volume.cc:9:2: error: #error This platform is not implemented yet
 #error This platform is not implemented yet
```

possibly [related](https://github.com/GravitAG/gravit/issues/229)

**Comment by comamitc** [comment]
Opened the following question on stackoverflow: 

http://stackoverflow.com/questions/28710232/conditionally-include-dependency-package-json

**Comment by shaunlebron** [comment]
cool, thanks for looking into this.  looks like the optionalDependencies is the solution
