### PR TITLE
Fixed #99: setup error on Ubuntu due to Mac OS dependencies

### LINKED ISSUE #99: macos-alias@0.2.6 fails to compile on ubuntu 14.02
```
> macos-alias@0.2.6 install /home/comamitc/dev/cuttle/node_modules/grunt-appdmg/node_modules/appdmg/node_modules/ds-store/node_modules/macos-alias
> node-gyp rebuild

make: Entering directory `/home/comamitc/dev/cuttle/node_modules/grunt-appdmg/node_modules/appdmg/node_modules/ds-store/node_modules/macos-alias/build'
  CXX(target) Release/obj.target/volume/src/volume.o
../src/volume.cc:9:2: error: #error This platform is not implemented yet
 #error This platform is not implemented yet
```

possibly [related](https://github.com/GravitAG/gravit/issues/229)

### PR DESCRIPTION
**Pull request by comamitc**

### CODE REVIEW

**Comment by shaunlebron** [comment]
thanks
